export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const GET_SERVICE = "GET_SERVICE";
export const ADD_SERVICE = "ADD_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const LOAD_SERVICE = "LOAD_SERVICE";
export const FAIL_SERVICE = "FAIL_SERVICE";
export const GET_ALL_SERVICES_BY_USER = " GET_ALL_SERVICES_BY_USER";
